### ISSUE TITLE
Namespace templating

### ISSUE THREAD

**Issue by rielas** [NeuraLegion/helmcharts#4]
https://github.com/NeuraLegion/helmcharts/blob/0f289c1f26aebb968070844481f8d3bfc611cf4d/charts/dvwa/templates/deployment.yaml#L6

Needs to be transformed, as in [BrokenCrystals](https://github.com/NeuraLegion/helmcharts/blob/0f289c1f26aebb968070844481f8d3bfc611cf4d/charts/brokencrystals/templates/bc-prod-deployment.yaml#L6). The same applies for all other `namespace` entries

**Comment by gornication** [comment]
Added namespace [template variable](https://github.com/NeuraLegion/helmcharts/blob/main/charts/dvwa/templates/deployment.yaml#:~:text=namespace%3A-,%7B%7B%20.Release.Namespace%20%7D%7D,-labels%3A)
